# Generated by Django 3.2.8 on 2021-10-19 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=18, verbose_name='api key')),
                ('api_secret', models.CharField(max_length=36, verbose_name='api secret')),
                ('date_register', models.DateTimeField(verbose_name='дата регистрации')),
                ('bybit_user_id', models.CharField(max_length=50, verbose_name='id пользователя bybit')),
                ('subscription_status', models.CharField(max_length=13, verbose_name='статус подписки')),
                ('wallet_address', models.CharField(max_length=40, verbose_name='адрес кошелька')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
                'db_table': 'profile',
            },
        ),
    ]
