# Generated by Django 3.2.8 on 2021-10-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BybitInformationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=18, verbose_name='api key')),
                ('api_secret', models.CharField(max_length=36, verbose_name='api secret')),
                ('bybit_user_id', models.CharField(max_length=50, verbose_name='id пользователя bybit')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bybit_user_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='bybit_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_app.bybitinformationclient', verbose_name='информация с bybit'),
        ),
    ]
