# Generated by Django 3.2.8 on 2021-10-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20211020_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bybitinformationclient',
            options={'verbose_name': 'информация с bybit', 'verbose_name_plural': 'информация с bybit'},
        ),
        migrations.AlterModelTable(
            name='bybitinformationclient',
            table='bybit information',
        ),
    ]
