# Generated by Django 3.2.8 on 2021-10-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20211020_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bybit_info',
        ),
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(default=None, max_length=18, verbose_name='api key'),
        ),
        migrations.AddField(
            model_name='profile',
            name='api_secret',
            field=models.CharField(default=None, max_length=36, verbose_name='api secret'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bybit_user_id',
            field=models.CharField(default=None, max_length=50, verbose_name='id пользователя bybit'),
        ),
        migrations.DeleteModel(
            name='BybitInformationClient',
        ),
    ]
