# Generated by Django 3.2.8 on 2021-11-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mailing',
            field=models.BooleanField(default=None, verbose_name='Рассылка'),
        ),
    ]
