# Generated by Django 3.2.8 on 2021-11-21 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0006_profile_mailing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(verbose_name='день')),
                ('month', models.FloatField(verbose_name='месяц')),
                ('year', models.FloatField(verbose_name='год')),
                ('sum_paid', models.FloatField(verbose_name='сумма')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'доходность',
                'verbose_name_plural': 'доходности',
                'db_table': 'profit',
            },
        ),
    ]
