# Generated by Django 3.2.8 on 2021-11-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='day',
            field=models.FloatField(verbose_name='день'),
        ),
    ]
